apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: zuefnf0ja-go 
  janus-idp.io/tekton: zuefnf0ja-go
  backstage.io/kubernetes-id: zuefnf0ja-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zuefnf0ja-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml